<?php

function statepoll_menu() {
    $items['statepoll'] = array(
        'title' => 'State Poll',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('statepoll_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
        $items['statepoll_success_page'] = array(
        'title' => 'Success',
        'page callback' => 'statepoll_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function statepoll_form() {
    $form['icecream_flavor'] = array(
        '#title' => 'Favorite ice cream',
        '#type' => 'textfield',
        '#description' => t('What is your favorite flavor ice cream?'),
    );

    $form['state'] = array(
        '#title' => 'State',
        '#type' => 'textfield',
        '#description' => t('What state do you live in?'),
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Go!',
    );

    return $form;
}

function statepoll_form_validate($form, &$form_state) {
  $states = array("Alabama","AL","Alaska","AK","Arizona","AZ","Arkansas","AR","California","CA","Colorado","CO","Connecticut","CT","Delaware","DE","Florida","FL","Georgia","GA","Hawaii","HI","Idaho","ID","Illinois","IL","Indiana","IN","Iowa","IA","Kansas","KS","Kentucky","KY","Louisiana","LA","Maine","ME","Maryland","MD","Massachusetts","MA","Michigan","MI","Minnesota","MN","Mississippi","MS","Missouri","MO","Montana","MT","Nebraska","NE","Nevada","NV","New Hampshire","NH","New Jersey","NJ","New Mexico","NM","New York","NY","North Carolina","NC","North Dakota","ND","Ohio","OH","Oklahoma","OK","Oregon","OR","Pennsylvania","PA","Rhode Island","RI","South Carolina","SC","South Dakota","SD","Tennessee","TN","Texas","TX","Utah","UT","Vermont","VT","Virginia","VA","Washington","WA","West Virginia","WV","Wisconsin","WI","Wyoming","WY");

  $state = strtolower($form_state['values']['state']);
  $states = array_map('strtolower', $states);

  if (!in_array($state, $states)) {
     form_set_error('state', 'That\'s not a US State');
  }
}

function statepoll_form_submit($form, &$form_state) {

    $icecream_flavor = $form_state['values']['icecream_flavor'];
    $state = $form_state['values']['state'];


    $_SESSION['icecream_flavor'] = $icecream_flavor;
    $_SESSION['state'] = $state;
    $form_state['redirect'] = 'statepoll_success_page';
}

function statepoll_success() {
    $output = $_SESSION['icecream_flavor'] . ' is the flavor you chose in ' . $_SESSION['state'];
    return $output;
}
